### ISSUE TITLE
randomize TLS ciphers

### ISSUE THREAD

**Issue by catdevnull** [the-convocation/twitter-scraper#89]
https://github.com/imputnet/cobalt/pull/574

**Comment by karashiiro** [comment]
Linking #49, #77

**Comment by karashiiro** [comment]
This is pretty involved for this project because it's Node-specific, so it actually implies setting up a new build system that can support that (or doing dynamic `require`s which don't get transformed in `esbuild`, or bundlerless polyfills which aren't fun).

At that point it's trivial to tack #22 onto this too - got this implemented on [a branch](https://github.com/the-convocation/twitter-scraper/compare/main...karashiiro:twitter-scraper:feat/node-tls-shuffling) today. I still need to clean up a couple parts of this, but it does seem to help with 404s sometimes.
